#' Read data file generated from P3 simulation v8
#'
#' temporary helper functions, will not be included in final package.
#'
#' @param file file path
#'
#' @return matrix
#' @export
read_data <- function(file) {
  out <- utils::read.table(file)
  out <- out[, -c(1, 3, 4, 5, 6, 7)]
  out <- as.matrix(out)
  apply(out, 2, as.numeric)
}


#' Read dag file generated from P3 simulation v8
#'
#' temporary helper functions, will not be included in final package.
#'
#' @param file file path
#' @param data matrix generated by read_data
#' @param maxpar maximun number of parents for a node
#'
#' @return names list with 4 elements
#' @export
read_dag <- function(file, data, maxpar) {
  dag_data <- readLines(file)
  dag_info <- list(
    nodetype = as.integer(substr(dag_data, 4, 4)),
    Npar = as.integer(substr(dag_data, 1, 1))
  )

  par <- matrix(0, nrow = ncol(data), ncol = maxpar)

  node_pars <- lapply(strsplit(substr(dag_data, 7, nchar(dag_data)), "  "), as.numeric)

  for (i in seq_along(dag_info$Npar)) {
    if(dag_info$Npar[i] > 0) {
      par[i, seq_along(node_pars[[i]])] <- node_pars[[i]]
    }
  }

  mode(par) <- "integer"

  dag_info$par <- par
  dag_info$MaxPar <- maxpar
  dag_info
}
