# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_network <- function(X, Npar, nodetype, par, MaxPar, phi = 1, omega = 6.9, InitialNetwork = 2L) {
    .Call(`_bayesnetworks_fit_network`, X, Npar, nodetype, par, MaxPar, phi, omega, InitialNetwork)
}

